# Generated by Django 6.0.7 on 2026-07-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
